/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.schlibbuz.commons.argsscanner;

import java.util.Arrays;
import java.util.LinkedList;
import java.util.List;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class ArgsScanner {

    private static final Logger w = LogManager.getLogger(ArgsScanner.class);
    private static final String AS_CONFIG_JSON = "src/main/resources/as.config.json";

    private final ArgsScannerConfig config;
    private final String originalArgsLine;


    public ArgsScanner(String[] args) {
        originalArgsLine = dumpArgs(args);
        w.trace(originalArgsLine);
        config = ArgsScannerConfig.fromJSON(AS_CONFIG_JSON);
    }

    String dumpArgs(String[] args) {

        if (args.length == 0) return "";

        var s = new StringBuilder();
        for (var arg : args) {
            s.append(arg).append(" ");
        }
        return s.deleteCharAt(s.length()-1).toString();
    }

    List<String> normalizeArgs(String[] args) {
        var argsList = new LinkedList<String>(Arrays.asList(args));

        if (argsList.isEmpty()) {
            argsList.add(config.get("runmodes->default"));
            argsList.add(config.get("target-default"));
            return argsList;
        }

        return argsList;
    }
}
